<?php
echo 'Hello World!';
echo '<br>';
echo '<br>';
echo '<a href="index.html" target="_blank">index.html</a>';
echo '<br>';
echo '<a href="variables.php" target="_blank">variables.php</a>';
echo '<br>';
echo '<a href="main.php" target="_blank">main.php</a>';
echo '<br>';
echo '<a href="arrays.php" target="_blank">arrays.php</a>';
echo '<br>';
echo '<a href="whileloop.php">whileloop.php</a>';
echo '<br>';
echo '<a href="comparison.php" target="_blank">comparison.php</a>';
echo '<br>';
echo '<a href="controlstructures.php" target="_blank">controlstructures.php</a>';
echo '<br>';
echo '<a href="forloop.php" target="_blank">forloop.php</a>';
echo '<br>';
echo '<a href="elseif.php" target="_blank">elseif.php</a>';
echo '<br>';
echo '<a href="switch.php" target="_blank">switch.php</a>';
echo '<br>';
echo '<a href="mixedphphtmlassignment.php" target="_blank">mixedphphtmlassignment.php</a>';
echo '<br>';
echo '<a href="databases.php" target="_blank">databases.php</a>';
echo '<br>';
echo '<a href="dbconnect.php" target="_blank">dbconnect.php</a>';
echo '<br>';
echo '<a href="databases_withdb_posts.php" target="_blank">databases_withdb_posts.php</a>';
echo '<br>';
echo '<a href="querystring.php" target="_blank">querystring.php</a>';
echo '<br>';
echo '<a href="form.php" target="_blank">form.php</a>';
echo '<br>';
echo '<a href="form2.php" target="_blank">form2.php</a>';
echo '<br>';
echo '<a href="new_article.php" target="_blank">add new article</a>';
echo '<br>';
echo '<a href="new-article-2.php" target="_blank">new article version 2</a>';
