CREATE DATABASE cms;
CREATE USER 'cms_www'@'localhost' IDENTIFIED BY 'Guruji123$';

GRANT EXECUTE, PROCESS, SELECT, SHOW DATABASES, SHOW VIEW, ALTER, ALTER ROUTINE, CREATE, CREATE ROUTINE, CREATE TABLESPACE, CREATE TEMPORARY TABLES, CREATE VIEW, DELETE, DROP, EVENT, INDEX, INSERT, REFERENCES, TRIGGER, UPDATE, CREATE USER, FILE, LOCK TABLES, RELOAD, REPLICATION CLIENT, REPLICATION SLAVE, SHUTDOWN, SUPER  ON *.* TO 'cms_www'@'localhost' WITH GRANT OPTION;
GRANT EXECUTE, SELECT, SHOW VIEW, ALTER, ALTER ROUTINE, CREATE, CREATE ROUTINE, CREATE TEMPORARY TABLES, CREATE VIEW, DELETE, DROP, EVENT, INDEX, INSERT, REFERENCES, TRIGGER, UPDATE, LOCK TABLES  ON `cms`.* TO 'cms_www'@'localhost' WITH GRANT OPTION;
FLUSH PRIVILEGES;

CREATE TABLE `article` (
	`id` INT NOT NULL AUTO_INCREMENT,
	`title` VARCHAR(128) NOT NULL,
	`content` TEXT NOT NULL,
	`published_at` DATETIME NULL,
	PRIMARY KEY (`id`)
)
COMMENT='This table will store articles information'
COLLATE='utf8mb4_unicode_ci'
;

INSERT INTO `article` (`id`, `title`, `content`, `published_at`) 
VALUES (NULL, 'First Post', 'An awesome first post on Mindful walking.', '2023-08-22 09:12:36');

INSERT INTO article (`id`, `title`, `content`, `published_at`)
VALUES (NULL, 'Second Post', 'Second post is too good.', '2023-02-23 09:46:56'); 